swagger: '2.0'
info:
  title: GPTE Coolstore Cart API
  description: Shopping Cart for the Coolstore
  version: 1.0.0
schemes:
  - http
basePath: /
produces:
  - application/json
paths:
  /cart/{cartId}:
    get:
      summary: Get a shopping cart by ID
      description: |
        This endpoint returns a shopping cart
      responses:
        '200':
          description: A shopping cart
          schema:
            type: object